#include "FredkinKoehlerApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<FredkinKoehlerApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

FredkinKoehlerApp::FredkinKoehlerApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  FredkinKoehlerApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  FredkinKoehlerApp::associateSyntax(_syntax, _action_factory);
}

FredkinKoehlerApp::~FredkinKoehlerApp()
{
}

// External entry point for dynamic application loading
extern "C" void FredkinKoehlerApp__registerApps() { FredkinKoehlerApp::registerApps(); }
void
FredkinKoehlerApp::registerApps()
{
  registerApp(FredkinKoehlerApp);
}

// External entry point for dynamic object registration
extern "C" void FredkinKoehlerApp__registerObjects(Factory & factory) { FredkinKoehlerApp::registerObjects(factory); }
void
FredkinKoehlerApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void FredkinKoehlerApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { FredkinKoehlerApp::associateSyntax(syntax, action_factory); }
void
FredkinKoehlerApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
