#include "KoalaApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<KoalaApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

KoalaApp::KoalaApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  KoalaApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  KoalaApp::associateSyntax(_syntax, _action_factory);
}

KoalaApp::~KoalaApp()
{
}

// External entry point for dynamic application loading
extern "C" void KoalaApp__registerApps() { KoalaApp::registerApps(); }
void
KoalaApp::registerApps()
{
  registerApp(KoalaApp);
}

// External entry point for dynamic object registration
extern "C" void KoalaApp__registerObjects(Factory & factory) { KoalaApp::registerObjects(factory); }
void
KoalaApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void KoalaApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { KoalaApp::associateSyntax(syntax, action_factory); }
void
KoalaApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
